name: Build and Deploy
on:
  push:
    branches: [masterq]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Build
        run: echo Github Action Running
